sudo: false
language: python
python:
  - "2.7"
before_install:
  - cabal update
  - cabal install pandoc
install:
  - python setup.py install
script: nosetests test/
after_success:
  - pip install coveralls --use-mirrors
  - coveralls
